version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies using Yarn
          command: |
            yarn install
            yarn global add vite
      - persist_to_workspace:
          root: ~/project  # ✅ Diperbaiki dari ~/repo
          paths:
            - node_modules
            - yarn.lock
            - .nx

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run build for all packages
          command: yarn build

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
