version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies using Yarn
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - yarn.lock
            - .nx

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run build for all packages
          command: yarn build

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run all tests
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
